var math = parseFloat(75.25);
var biology = parseInt(65);
var chemistry = parseInt(80);
var physics = parseFloat(35.45);
var bangla = 99.50;
var totalMarks = math + biology + chemistry + physics + bangla;
console.log(totalMarks);
var averageMarks = totalMarks / 5;
console.log(averageMarks);
var twoDecimals = averageMarks.toFixed(2);
console.log(twoDecimals);